appName: decorator-next
appPath: ''
port: 8089
ingresses:
  - https://decorator-next.ekstern.dev.nav.no
outboundHosts:
  - www.nav.no
  - www.intern.dev.nav.no
  - navno-unleash-api.nav.cloud.nais.io
  - tokendings.dev-gcp.nais.io
env:
  - name: ENV
    value: NAV_NO
  - name: XP_BASE_URL
    value: https://www.ekstern.dev.nav.no
  - name: APP_BASE_URL
    value: https://dekoratoren.ekstern.dev.nav.no
  - name: API_XP_SERVICES_URL
    value: https://portal-admin-dev.oera.no/_/service
  - name: API_DEKORATOREN_URL
    value: https://www.ekstern.dev.nav.no/person/nav-dekoratoren-api
  - name: MINSIDE_ARBEIDSGIVER_URL
    value: https://min-side-arbeidsgiver.intern.dev.nav.no/min-side-arbeidsgiver/
  - name: MIN_SIDE_URL
    value: https://www.intern.dev.nav.no/minside/
  - name: LOGIN_URL
    value: https://login.ekstern.dev.nav.no/oauth2/login
  - name: LOGOUT_URL
    value: https://login.ekstern.dev.nav.no/oauth2/logout
  - name: VARSEL_API_URL
    value: https://www.intern.dev.nav.no/tms-varsel-api
replicas:
  min: 1
  max: 2
resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    memory: 512Mi
