appName: decorator-next
appPath: ''
ingresses:
  - https://www.nav.no/decorator-next
outboundHosts:
  - www.nav.no
  - www.intern.dev.nav.no
  - navno-unleash-api.nav.cloud.nais.io
  - tokendings.dev-gcp.nais.io
env:
  - name: ENV
    value: NAV_NO
  - name: HOST
    value: https://www.nav.no/decorator-next
  - name: CDN_URL
    value: https://cdn.nav.no/personbruker/decorator-next/public
  - name: ENONICXP_SERVICES
    value:  https://www.nav.no/_/service
  - name: XP_BASE_URL
    value: https://www.nav.no
  - name: AUTH_API_URL
    value: https://login.dev.nav.no
  - name: LOGIN_URL
    value: https://login.nav.no/oauth2/login
  - name: LOGOUT_URL
    value: https://login.nav.no/oauth2/logout
  - name: VARSEL_API_URL
    value: https://www.nav.no/tms-varsel-api
  - name: API_DEKORATOREN_URL
    value: https://www.nav.no/person/nav-dekoratoren-api
  - name: API_SESSION_URL
    value: https://login.nav.no/oauth2/session
  - name: MIN_SIDE_URL
    value: https://www.nav.no/minside/
  - name: MIN_SIDE_ARBEIDSGIVER_URL
    value: https://www.intern.dev.nav.no/min-side-arbeidsgiver
  - name: PERSONOPPLYSNINGER_URL
    value: https://www.nav.no/person/personopplysninger
  - name: CASETYPE_ID
    value: 66D660EF-6F14-44B4-8ADE-A70A127202D0
  - name: NAV_GROUP_ID
    value: A034081B-6B73-46B7-BE27-23B8E9CE3079
  - name: OPPORTUNITY_ID
    value: 615FF5E7-37B7-4697-A35F-72598B0DC53B
  - name: SOLUTION_ID
    value: 5EB316A1-11E2-460A-B4E3-F82DBD13E21D
replicas:
  min: 1
  max: 2
resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    memory: 512Mi
