---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: {{appName}}
  namespace: personbruker
  labels:
    team: personbruker
  annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: "256M"
      nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
spec:
  image: {{image}}
  port: 8089
  liveness:
    path: /api/isAlive
    initialDelay: 10
  readiness:
    path: /api/isReady
    initialDelay: 10
  prometheus:
    enabled: true
    path: {{appPath}}/metrics
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
  accessPolicy:
    outbound:
      external:
        {{#each outboundHosts as |host|}}
        - host: {{host}}
        {{/each}}
    inbound:
      rules:
        - application: "*"
          namespace: "*"
  env:
  {{#each env as |var|}}
    - name: {{var.name}}
      value: {{var.value}}
  {{/each}}
  replicas:
  {{#with replicas}}
    min: {{min}}
    max: {{max}}
  {{/with}}
  resources:
  {{#with resources}}
    requests:
      cpu: {{requests.cpu}}
      memory: {{requests.memory}}
    limits:
      memory: {{limits.memory}}
  {{/with}}

