apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: decorator-next
  namespace: personbruker
  labels:
    team: personbruker
spec:
  image: {{image}}
  port: 8089
  idporten:
    enabled: true
    sidecar:
      enabled: true
      level: Level4
  tokenx:
    enabled: true
  ingresses:
    - https://decorator-next.ekstern.dev.nav.no
  liveness:
    path: /api/isAlive
    initialDelay: 10
  readiness:
    path: /api/isReady
    initialDelay: 10
  accessPolicy:
    outbound:
      external:
        - host: www.nav.no
        - host: www.intern.dev.nav.no
        - host: navno-unleash-api.nav.cloud.nais.io
      rules:
        - application: tms-varsel-api
          namespace: min-side
  replicas:
    min: 1
    max: 2
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      memory: 512Mi
  env:
    - name: HOST
      value: https://decorator-next.ekstern.dev.nav.no
    - name: PORT
      value: '8089'
  envFrom:
    - secret: nav-dekoratoren-unleash-api-token
