apiVersion: unleash.nais.io/v1
kind: ApiToken
metadata:
  name: decorator-next
  namespace: personbruker
  labels:
    team: personbruker
spec:
  unleashInstance:
    apiVersion: unleash.nais.io/v1
    kind: RemoteUnleash
    name: navno
  secretName: decorator-next-unleash-api-token
  environment: development
