apiVersion: v1
kind: ConfigMap
metadata:
  name: dekoratoren-version-authority-{{deployInstance}}
  namespace: personbruker
  labels:
    team: personbruker
data:
  AUTHORITATIVE_VERSION_ID: "{{versionId}}"
