name: Build and deploy to nais
on:
  workflow_call:
    inputs:
      NAIS_VARS:
        required: true
        type: string
      IMAGE_NAME:
        required: true
        type: string
      CLUSTER:
        required: true
        type: string

jobs:
  build_and_deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    env:
      image: ghcr.io/${{ github.repository }}:${{ inputs.IMAGE_NAME }}-${{ github.sha }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: '1.0.25'
      - name: Install dependencies
        run: bun install --immutable
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - name: Build app
        run: bun run build
      - name: Run tests
        run: bun run test
      - name: upload to CDN
        uses: navikt/frontend/actions/cdn-upload/v1@main
        with:
          cdn-team-name: personbruker
          source: './packages/server/public'
          destination: '/decorator-next'

      - name: Build and push docker image
        uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: personbruker
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          image_suffix: ${{ inputs.environment }}

      - uses: nais/deploy/actions/deploy@master
        env:
          CLUSTER: ${{ inputs.CLUSTER }}
          RESOURCE: .nais/config.yml
          VAR: image=${{ steps.docker-push.outputs.image }},BUILD_ID=${{ github.sha }}
          VARS: ${{ inputs.NAIS_VARS }}
