name: Build docker image
on:
  workflow_call:
    inputs:
      DEPLOY_INSTANCE:
        required: true
        type: string
      CLUSTER:
        required: true
        type: string
    outputs:
      image:
        description: "Docker image"
        value: ${{ jobs.build_image.outputs.image }}
    secrets:
      READER_TOKEN:
        required: true
      NAIS_WORKLOAD_IDENTITY_PROVIDER:
        required: true

jobs:
  build_image:
    name: Build and deploy
    runs-on: ubuntu-latest
    environment: ${{ inputs.DEPLOY_INSTANCE }}
    permissions:
      contents: read
      id-token: write
    outputs:
      image: ${{ steps.docker-push.outputs.image }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.11
      - name: Install dependencies
        run: bun install --immutable --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - name: Build app
        run: bun run build
      - name: Run unit tests
        run: bun run test
      - name: Run playwright tests
        run: |
          bunx playwright install --with-deps
          cp packages/server/.env.sample packages/server/.env
          bunx playwright test
      - name: Upload static files to NAV CDN
        uses: nais/deploy/actions/cdn-upload/v2@master
        with:
          team: personbruker
          source: './packages/server/public'
          destination: '/decorator-next'
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
      - name: Build and push docker image
        uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: personbruker
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          image_suffix: ${{ inputs.DEPLOY_INSTANCE }}
