name: Deploy to dev
on:
  workflow_dispatch:
  push:
    branches:
      - main
env:
  IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: '1.0.1'
      - name: Define app environmment
        run: |
            cat > .env <<EOF
            ENV=production
            VITE_DECORATOR_BASE_URL=https://decorator-next.ekstern.dev.nav.no
            ENONICXP_SERVICES=https://www.intern.dev.nav.no/_/service
            VITE_DECORATOR_API=https://www.ekstern.dev.nav.no/person/nav-dekoratoren-api
            VITE_AUTH_API=https://login.ekstern.dev.nav.no
            VITE_LOGIN_URL=https://login.ekstern.dev.nav.no/oauth2/login
            VITE_LOGOUT_URL=https://login.ekstern.dev.nav.no/oauth2/logout
            PORT=3000
            EOF
      - name: Install dependencies
        run: bun install --immutable
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - name: Run tests
        run: bun test
      - name: Build app
        run: bun run build
      - name: Login to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: 'ghcr.io'
          username: '${{ github.actor }}'
          password: '${{ secrets.GITHUB_TOKEN }}'
      - name: Build and push Docker
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          tags: '${{ env.IMAGE }}'
          push: 'true'
  deploy:
    name: Deploy app
    needs: 'build'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
      - name: Deploy app
        uses: 'nais/deploy/actions/deploy@v1'
        env:
          'APIKEY': '${{ secrets.NAIS_DEPLOY_APIKEY }}'
          'CLUSTER': 'dev-gcp'
          'RESOURCE': '.nais/config-dev.yml'
