name: Deploy intern app-versjon
on:
  workflow_dispatch:
    inputs:
      image:
        description: "Docker image"
        required: true
        type: string
      versionId:
        description: "Version id"
        required: true
        type: string
      cluster:
        description: 'Cluster'
        required: true
        type: choice
        options:
          - prod-gcp
          - dev-gcp
      varsFile:
        description: 'Vars file'
        required: true
        type: choice
        options:
          - dev-beta-navno
          - dev-stable
          - prod

jobs:
  deploy_internal:
    name: Deploy intern app-versjon
    runs-on: ubuntu-latest
    environment: ${{ inputs.DEPLOY_INSTANCE }}
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Deploy internal versioned app
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: ${{ inputs.cluster }}
          RESOURCE: .nais/config-internal.yml
          VAR: image=${{ inputs.image }},versionId=${{ inputs.versionId }}
          VARS: .nais/vars/${{ inputs.varsFile }}.yml
