name: Deploy unleash-apitoken
on:
  push:
    paths:
      - ".nais/unleash-api-token.dev.yaml"
      - ".nais/unleash-api-token.prod.yaml"

jobs:
  deploy-dev:
    name: Deploy unleash-apitoken to dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy application
        uses: nais/deploy/actions/deploy@master
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/unleash-api-token.dev.yaml

  deploy-prod:
    name: Deploy unleash-apitoken to prod
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy application
        uses: nais/deploy/actions/deploy@master
        if: github.ref == 'refs/heads/main'
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/unleash-api-token.prod.yaml