name: Deploy to dev
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: ./.github/workflows/build-and-deploy.yml
    permissions:
      id-token: write
      contents: read
    with:
      DEPLOY_INSTANCE: dev-stable
      CLUSTER: dev-gcp
    secrets: inherit
