name: Deploy to dev
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    permissions:
      packages: write
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      NAIS_VARS: .nais/vars/dev.yml
      IMAGE_NAME: decorator-next
      CLUSTER: dev-gcp
    secrets: inherit

