name: Deploy to prod
on:
  release:
    types: [released]

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read
    if: github.event.release.target_commitish == 'main'
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      DEPLOY_INSTANCE: prod
      CLUSTER: prod-gcp
    secrets: inherit
