name: Deploy to dev
on:
  workflow_dispatch:
  push:
    branches:
      - main
env:
  IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: '1.0.9'
      - name: Define app environmment
        run: |
            cat > .env <<EOF
            ENV=NAV_NO
            HOST=https://decorator-next.ekstern.dev.nav.no
            CDN_URL=https://decorator-next.ekstern.dev.nav.no
            ENONICXP_SERVICES=https://www.intern.dev.nav.no/_/service
            AUTH_API_URL=https://login.ekstern.dev.nav.no
            LOGIN_URL=https://login.ekstern.dev.nav.no/oauth2/login
            LOGOUT_URL=https://login.ekstern.dev.nav.no/oauth2/logout
            VARSEL_API_URL=https://www.intern.dev.nav.no/tms-varsel-api
            PORT=8089
            EOF
      - name: Install dependencies
        run: bun install --immutable
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - name: Build app
        run: bun run build
      - name: Run tests
        run: bun run test
      - name: Login to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: 'ghcr.io'
          username: '${{ github.actor }}'
          password: '${{ secrets.GITHUB_TOKEN }}'
      - name: Build and push Docker
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          tags: '${{ env.IMAGE }}'
          push: 'true'
  upload:
    name: 'Upload to CDN'
    needs: 'build'
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: 'actions/checkout@v3'
      - id: upload
        uses: navikt/frontend/actions/cdn-upload/v1@main
        with:
          cdn-team-name: personbruker
          source: './packages/server/public'
          destination: '/'

      - run: echo uploaded file ${{ steps.upload.outputs.uploaded }}
        shell: bash

  deploy:
    name: Deploy app
    needs: 'build'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: navikt/frontend/actions/cdn-upload/v1@main
        name: Upload to CDN
        with:
          cdn-team-name: personbruker
          source: './packages/server/public'
          destination: '/decorator-next-dev/'

      - uses: actions/checkout@v3
      - name: Deploy app
        uses: 'nais/deploy/actions/deploy@v1'
        env:
          'APIKEY': '${{ secrets.NAIS_DEPLOY_APIKEY }}'
          'CLUSTER': 'dev-gcp'
          'RESOURCE': '.nais/config-dev.yml'
