name: Deploy to prod
on:
  push:
    branches:
      - main
    paths-ignore:
      - ./README.md

jobs:
  build:
    uses: ./.github/workflows/build-image.yml
    permissions:
      id-token: write
      contents: read
    with:
      IMAGE_SUFFIX: prod
    secrets: inherit

  deploy-prod:
    uses: ./.github/workflows/deploy-application.yml
    needs: build
    permissions:
      id-token: write
      contents: read
    with:
      DEPLOY_INSTANCE: prod
      CLUSTER: prod-gcp
      IMAGE: ${{ needs.build.outputs.IMAGE }}
      DEPLOY_INTERNAL: true
    secrets:
      VARS_UPDATE_TOKEN: ${{ secrets.VARS_UPDATE_TOKEN }}

  deploy-dev-stable:
    uses: ./.github/workflows/deploy-application.yml
    needs: build
    permissions:
      id-token: write
      contents: read
    with:
      DEPLOY_INSTANCE: dev-stable
      CLUSTER: dev-gcp
      IMAGE: ${{ needs.build.outputs.IMAGE }}
    secrets:
      VARS_UPDATE_TOKEN: ${{ secrets.VARS_UPDATE_TOKEN }}

  deploy-beta-navno:
    uses: ./.github/workflows/deploy-application.yml
    needs: build
    permissions:
      id-token: write
      contents: read
    with:
      DEPLOY_INSTANCE: dev-beta-navno
      CLUSTER: dev-gcp
      IMAGE: ${{ needs.build.outputs.IMAGE }}
    secrets:
      VARS_UPDATE_TOKEN: ${{ secrets.VARS_UPDATE_TOKEN }}

  deploy-beta-tms:
    uses: ./.github/workflows/deploy-application.yml
    needs: build
    permissions:
      id-token: write
      contents: read
    with:
      DEPLOY_INSTANCE: dev-beta-tms
      CLUSTER: dev-gcp
      IMAGE: ${{ needs.build.outputs.IMAGE }}
    secrets:
      VARS_UPDATE_TOKEN: ${{ secrets.VARS_UPDATE_TOKEN }}
