name: Playwright Tests
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v1
      with:
        bun-version: '1.1.4'
    - name: Install dependencies
      run: bun install --immutable --ignore-scripts
      env:
        NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
    - name: Build app
      run: bun run build
    - name: Install Playwright Browsers
      run: bun --bun x playwright install --with-deps
    - name: Run Playwright tests
      run: bun --bun x playwright test
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
