name: Release

on:
  push:
    branches:
      - auto-release

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: '1.1.4'
      - name: Install dependencies
        run: bun install --immutable --ignore-scripts --production
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - run: bun run build
      - run: bun run test
      - run: bunx playwright install --with-deps
      - run: cp packages/server/.env.sample packages/server/.env
      - run: bunx playwright test

  create-release:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Release
      uses: softprops/action-gh-release@v2